### ISSUE TITLE
Show survey when the user uninstalls the extension

### ISSUE THREAD

**Issue by Mahmoud-Skafi** [abozanona/luca#52]
Create a survey when the user uninstalls the extension

**Comment by Mahmoud-Skafi** [comment]
chrome.runtime.setUninstallURL(`https://docs.google.com/forms/d/e/1FAIpQLSd8Z6m6lAFwLk88WK8arSgMfIcJxhVROR3r64RlCo-Lfs_0rA/viewform?entry.435513449=${user.agent}&entry.126853255=${user.version}`);

**Comment by abozanona** [comment]
Form link: https://docs.google.com/forms/d/e/1FAIpQLSchwIEPLVcl54IOHZOrQ8s_2jyWE_ea2Njk8kajZtUwPmNFcQ/viewform?usp=sf_link
